services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: kino
      POSTGRES_PASSWORD: kino_password
      POSTGRES_DB: kino_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
